version: "3"

services:
  mysql:
    image: mysql:5.7.8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal7
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - drupal7_net

  drupal:
    #build: .
    image: prashanthdevaraj/drupal7:latest
    container_name: drupal
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    networks:
      - drupal7_net
networks:
  drupal7_net:
    driver: bridge
